IMG_DIR: "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/imgs/"
ANNOTATIONS_FULL: "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/chest_xray_positive_wbf.csv"
ANNOTATIONS_TRAIN: "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/chest_xray_positive_wbf_train.csv"
ANNOTATIONS_TRAIN_JSON : "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/chest_xray_positive_wbf_train.json"
ANNOTATIONS_VAL: "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/chest_xray_positive_wbf_val.csv"
ANNOTATIONS_VAL_JSON : "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/chest_xray_positive_wbf_val.json"
ANNOTATIONS_PREPROCESS_BEFORE_WBF: "../../../../mnt/data_lab513/ntnhan/CHEST-XRAY/5-classes/chest_xray_standard_add.csv"
CLASSES_NAME : ["Aortic enlargement", "Cardiomegaly", "ILD", "Infiltration", "Nodule/Mass"]
HEATMAP_SIZE : [500, 400]
COLOR : [[59, 238, 119], [206, 221, 133], [210, 224, 119], [211, 176, 166], [102, 65, 77]]
IOU_THR_NMS : 0.4
IOU_THR_WBF : 0.4
SKIP_BOX_THR_WBF : 0.21
THICKNESS : 5
INFO_DESCRIPTION : "Chest-Xray-Standard-Add"
INFO_URL : "https://github.com/DatacollectorVN/Chest-Xray-Version2"
INFO_VERSION : "2.0"
INFO_YEAR : 2021
INFO_CONTRIBUTOR : "Kos Nhan"
LIN_URL : "https://vinbigdata.org/en/"
LIN_ID : 0
LIN_NAME : "VinBigData"
IMGS_LIN : 0
IMGS_COCO_URL : ""
IMG_DATE_CAPTURED : "2021"
IMG_FLICKR_URL : ""
VAL_RATIO : 0.2
SEED : 42